### ISSUE TITLE
missing screen sizes .cfg

### ISSUE THREAD

**Issue by B-Nerd** [CadmiumRED/CadmiumREDs-Bezels#2]
for most people to make them plug & play we are missing a .cfg file that tell retroarch how big the game screen needs to be
so something like these lines 
aspect_ratio_index = "23"
custom_viewport_height = "1093"
custom_viewport_width = "1291"
custom_viewport_x = "300"
input_overlay_opacity = "1.000000"
video_scale_integer = "false"
this is for 1080p monitors & uses this overlay 
![MSX](https://github.com/user-attachments/assets/17d237df-27c5-4d12-b804-8a4c2793bc81)

**Comment by CadmiumRED** [comment]
Game Boy and Game Boy Color config files for both 1440p and 1080p have been made and posted on the GitHub's main page.
